<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "<?php echo $this->getProductName(); ?>",
  <?php if ($this->haveImages()): ?>
  "image": [<?php echo implode(",", $this->getImages()) ?>],
   <?php endif; ?>
  "description": "<?php echo $this->getDescription(); ?>",
  "sku": "<?php echo $this->getSku(); ?>",
  "brand": {
    "@type": "Thing",
    "name": "<?php echo $this->getBrandName(); ?>"
  },
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.4",
    "reviewCount": "89"
  },
  "offers": {
    "@type": "Offer",
    "priceCurrency": "<?php echo $this->getPriceCurrency(); ?>",
    "price": "<?php echo $this->getPrice(); ?>",
    "priceValidUntil": "<?php echo $this->getPriceValidUntil(); ?>",
    "itemCondition": "<?php echo $this->getItemCondition(); ?>",
    "availability": "<?php echo $this->getAvailability(); ?>",

    "seller": {
      "@type": "Organization",
      "name": "Executive Objects"
    }
  }
}








</script>