<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "<?php echo $this->getProductName(); ?>",
  <?php if ($this->haveImages()): ?>
  "image": [<?php echo implode(",", $this->getImages()) ?>],
   <?php endif; ?>
  "description": "<?php echo $this->getDescription(); ?>",
  "sku": "<?php echo $this->getSku(); ?>",
  "brand": {
    "@type": "Thing",
    "name": "<?php echo $this->getBrandName(); ?>"
  },
   <?php if ($this->haveReviews()): ?>
  "aggregateRating": {
    "@type": "AggregateRating",
    "bestRating": "100",
    "ratingValue": "<?php echo $this->getRatingSummary(); ?>",
    "reviewCount": "<?php echo $this->getReviewCount(); ?>"
  },
   <?php endif; ?>
  "offers": {
    "@type": "Offer",
    "priceCurrency": "<?php echo $this->getPriceCurrency(); ?>",
    "price": "<?php echo $this->getPrice(); ?>",
    "priceValidUntil": "<?php echo $this->getPriceValidUntil(); ?>",
    "itemCondition": "<?php echo $this->getItemCondition(); ?>",
    "availability": "<?php echo $this->getAvailability(); ?>"
  }
}
</script>